### ISSUE TITLE
Ansible errors when provisioning or deploying

### ISSUE THREAD

**Issue by nckrtl** [serversideup/spin#115]
### Current Behavior

I'm getting the following error when provisioning or deploying. Couldn't find any steps to execute upon switching to the latest version

8a1bbdba2ef55f43479765bcd2c354455c0eba90c2b286f1bf33df48e0bca838
usermod: user 'ansible' does not exist
Error changing user ID.
groupmod: group 'ansible' does not exist
Error changing group ID.
ERROR! Unable to create local directories(/etc/ansible/galaxy_cache): [Errno 13] Permission denied: b'/etc/ansible/galaxy_cache'

### Expected Behavior

Getting no errors

### Steps To Reproduce

I switched to version 2.2.0 on Mac and when doing spin provision or spin deploy production I get that error. 

### Environment

```markdown
v2.2.0 [stable] (User Installed)

Operating System Version:
ProductName:		macOS
ProductVersion:		15.0
BuildVersion:		24A335

Client: Docker Engine - Community
 Version:    27.3.1
 Context:    orbstack
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.17.1
    Path:     /Users/nckrtl/.docker/cli-plugins/docker-buildx
  compose: Docker Compose (Docker Inc.)
    Version:  v2.29.7
    Path:     /Users/nckrtl/.docker/cli-plugins/docker-compose

Server:
 Containers: 11
  Running: 0
  Paused: 0
  Stopped: 11
 Images: 9
 Server Version: 27.3.1
 Storage Driver: overlay2
  Backing Filesystem: btrfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7f7fdf5fed64eb6a7caf99b3e12efcf9d60e311c
 runc version: 2c9f5602f0ba3d9da1c2596322dfc4e156844890
 init version: de40ad0
 Security Options:
  seccomp
   Profile: builtin
  cgroupns
 Kernel Version: 6.10.12-orbstack-00282-gd1783374c25e
 Operating System: OrbStack
 OSType: linux
 Architecture: aarch64
 CPUs: 12
 Total Memory: 7.81GiB
 Name: orbstack
 ID: 58ca268f-f61e-4c30-8932-765046146df9
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine
```

**Comment by jaydrogers** [comment]
Weird! Could you try "spin prune" then try again?

**Comment by nckrtl** [comment]
Still the same, output when doing a new deploy:
```
🚀 Starting local Docker registry...
Unable to find image 'registry:2' locally
2: Pulling from library/registry
720f3032cd11: Pull complete
d259642272e5: Pull complete
6e496f333012: Pull complete
e961822193ae: Pull complete
b98a2db964ee: Pull complete
Digest: sha256:ac0192b549007e22998eb74e8d8488dcfe70f1489520c3b144a6047ac5efbe90
Status: Downloaded newer image for registry:2
dd14ac0d30c8cb0a90866c48ec7688d79ad1d70510d75d52be204cf9b64766e1
Unable to find image 'serversideup/ansible-core:2.17-alpine' locally
2.17-alpine: Pulling from serversideup/ansible-core
cf04c63912e1: Pull complete
f0d3d23155cb: Pull complete
b408c1b12cb3: Pull complete
130d9e44d8c3: Pull complete
982421215f73: Pull complete
bbe8605dca68: Pull complete
4f4fb700ef54: Pull complete
Digest: sha256:20de0268dd934ffa0cc74904cf1ee57b8c64b1b7fe95eaa87d1a815de5e7312e
Status: Downloaded newer image for serversideup/ansible-core:2.17-alpine
usermod: user 'ansible' does not exist
Error changing user ID.
groupmod: group 'ansible' does not exist
Error changing group ID.
```

**Comment by nckrtl** [comment]
After some debugging the error is coming from the docker run command in run_ansible() of the functions.sh file.

So I tried to run a simple disposable container with:
```
docker run --rm -it \
  -v "$HOME/.ssh:/home/ansible/.ssh" \
  -v "$(pwd):/ansible" \
  serversideup/ansible-core:2.17-alpine /bin/sh
```
This works just fine no errors

I then tried to add the PUID and PGID, which are by default 501 and 20 (I got those values from echoing them in run_ansible())
```
docker run --rm -it \
    -v "$HOME/.ssh:/home/ansible/.ssh" \
    -v "$(pwd):/ansible" \
    -e "PUID=501" \
    -e "PGID=20" \
    -e "RUN_AS_USER=nckrtl" \
    serversideup/ansible-core:2.17-alpine /bin/sh
```

Then I got a similar error:
```
usermod: user 'ansible' does not exist
Error changing user ID.
groupmod: group 'ansible' does not exist
Error changing group ID.
```

So I removed the PUID and PGID in run_ansible() like so:
```
  docker run --rm -it \
    -e "RUN_AS_USER=$(whoami)" \
    "${additional_docker_args[@]}" \
    "$SPIN_ANSIBLE_IMAGE" \
    "${args_without_options[@]}"
```

Then it works with and it won't show an error. So perhaps the default PUID and PGID is causing issues? My deploy command still doesn't work, seems the host/ip isn't read properly: 
```
🚇 Creating SSH tunnel to Docker registry...
Bad port '"22"'
❌ Failed to create SSH tunnel. Exiting...
🔧 Troubleshoot your connection by running:
ssh -p "22" deploy@20
```
Will update once I found out where the 20 is coming from.

**Comment by jaydrogers** [comment]
There could be two problems to this:

- Something in the Ansible image (it's really odd it can't find the Ansible user)
- I changed a function for getting variables out of an Ansible configuration file (it was having string be integer issues)


I'll push a fix as soon as I'm by a computer 😃

Sorry for the troubles!

**Comment by jaydrogers** [comment]
Okay, hopefully this works now 😃

Of course yesterday I did all my testing on my Windows box and macOS had different behavior because the default UIDs on Mac are lower numbers than Linux 🙃

## What I did
- I fixed the start up issue with the Ansible image. This is fixed in a new release (https://github.com/serversideup/docker-ansible/releases/tag/v0.3.1)
- I fixed the variable trimming issue In Spin (https://github.com/serversideup/spin/commit/c5158fe4d825e37059792e93a6b7a6face99bb0f)

## Next Steps
1. Run `spin update` to update Spin to v2.2.1
2. Run `spin prune`
3. Try again 😅

**Comment by nckrtl** [comment]
Did a prune and updated, (2.2.0 now) but still the same PUID of 501 and PGID of 20 by default, so it still wont work unless I remove
```
    -e "PUID=${SPIN_USER_ID}" \
    -e "PGID=${SPIN_GROUP_ID}" \
    -e "RUN_AS_USER=$(whoami)" \
 ```

**Comment by jaydrogers** [comment]
Strange! I can't replicate it on my end:

![Screenshot 2024-10-09 at 14 25 23](https://github.com/user-attachments/assets/4d5ef7b6-6e0a-4030-b07a-6170f1734f63)

### Command I ran
```bash
docker run --rm -it \
    -v "$HOME/.ssh/:/ssh/" \
    -v "$(pwd):/ansible" \
    -e "PUID=501" \
    -e "PGID=20" \
    -e "RUN_AS_USER=nckrtl" \
    docker.io/serversideup/ansible-core:2.17-alpine
```

### Confirm image version
Check to see if your image is updating?

```bash
docker pull serversideup/ansible-core:2.17-alpine
```

You can verify your image to mine like this (if you have `jq` installed):

```bash
docker inspect --format='{{json .Config.Labels}}' docker.io/serversideup/ansible-core:2.17-alpine | jq
```

You should see `v0.4.0`:
```
{
  "org.opencontainers.image.authors": "Jay Rogers (@jaydrogers)",
  "org.opencontainers.image.description": "Run Ansible anywhere with a lightwieght and powerful Docker image",
  "org.opencontainers.image.documentation": "https://github.com/serversideup/docker-ansible",
  "org.opencontainers.image.licenses": "GPL-3.0-or-later",
  "org.opencontainers.image.source": "https://github.com/serversideup/docker-ansible",
  "org.opencontainers.image.title": "serversideup/ansible-core",
  "org.opencontainers.image.url": "https://github.com/serversideup/docker-ansible",
  "org.opencontainers.image.vendor": "ServerSideUp",
  "org.opencontainers.image.version": "v0.4.0"
}
```

Let me know what error you're seeing if you're all up to date.

**Comment by jaydrogers** [comment]
# ⚠️ Important update
@nckrtl: I just noticed this:

> Did a prune and updated, (2.2.0 now)

You should be on **v2.2.1+**. Hopefully the update process works? If you ran `spin update` and you have a development version (where you cloned the repo on your computer), be sure to run a `git pull` from `main`.

**Comment by nckrtl** [comment]
I have the exact same output as you. Also for the docker run command you just shared. But when I do `spin provision -u root' for example I get:

```
PLAY [Setup and provision Docker Swarm servers with Spin.] ********************************************************************************************************

TASK [Gathering Facts] ********************************************************************************************************************************************
fatal: [<my-vps-ip-goes-here>]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: root@<my-vps-ip-goes-here>: Permission denied (publickey,password).", "unreachable": true}
```

With the removal of 
```
    -e "PUID=${SPIN_USER_ID}" \
    -e "PGID=${SPIN_GROUP_ID}" \
    -e "RUN_AS_USER=$(whoami)" \
```
I get my 1password ssh prompt and it provisions just fine.

**Comment by nckrtl** [comment]
> # ⚠️ Important update
> @nckrtl: I just noticed this:
> 
> > Did a prune and updated, (2.2.0 now)
> 
> You should be on **v2.2.1+**. Hopefully the update process works? If you ran `spin update` and you have a development version (where you cloned the repo on your computer), be sure to run a `git pull` from `main`.

Yeah did a git pull on main, am on 2.2.0

**Comment by jaydrogers** [comment]
Thanks for the update!

So here's the error we'll focus on:
```
"Failed to connect to the host via ssh: root@<my-vps-ip-goes-here>: Permission denied (publickey,password)."
```

This is hinting that either:
1. The user doesn't have permission to access your server (**if you already ran a provision, `root` no longer accepts SSH connections**)
2. There is a configuration issue in the SSH client (the Alpine Docker container that tries to act like your Mac for SSH)

I'm assuming this is a FRESH server, so let's debug the SSH 

### 🤓 Let's get nerdy... How SSH works in this image
All the magic with SSH works here:

https://github.com/serversideup/spin/blob/30a44d2353e68117237b4a337a9666de155e8604/lib/functions.sh#L951-L964

**Important components:**
1. `$HOME/.ssh` mounts to `/ssh` (notice the root directory)
2. If a `SSH_AUTH_SOCK` is set, we mount that too (matching the path of the host)

### How `PUID`, `PGID`, `RUN_AS_USER` come into play
This is from our [serversideup/docker-ansible](https://github.com/serversideup/docker-ansible/) image. We first create a default `ansible` user:

https://github.com/serversideup/docker-ansible/blob/4eead28dcb25d5118b8b84846e07be8446d63cd7/src/Dockerfile#L24-L25

When you set `PUID`, `PGID`, `RUN_AS_USER`, it will rename that default unprivileged user and have it mimic the user structure like what you have on your Mac. This is completed at start up with the entry point:

https://github.com/serversideup/docker-ansible/blob/4eead28dcb25d5118b8b84846e07be8446d63cd7/src/rootfs/entrypoint.sh#L34-L101

# 👉 Debugging SSH
Try running a container, separate from Spin:

```sh
# I specifically left mounting /ansible out for testing...
# I also enabled debug mode
docker run --rm -it \
    -v "$HOME/.ssh/:/ssh/" \
    -e "PUID=$(id -u)" \
    -e "PGID=$(id -g)" \
    -e "RUN_AS_USER=$(whoami)" \
    -e "DEBUG=true" \
    docker.io/serversideup/ansible-core:2.17-alpine sh
```

**Once inside the container**
See if you can change into the Home directory (`cd ~`) and inspect the permissions. The `~/.ssh` is a symlink to `/ssh`, but that should be fine. The symlink is 777 so that shouldn't be a problem. The contents of that folder should match the UID and GID of your container and host.

### Test SSH
You should even be able to run SSH from within this container. Depending on your Mac config, you might have to disable Unknown options to Alpine Linux. For example:

```bash
ssh -o IgnoreUnknown=UseKeychain user@host
```

# 👉  Debug Provision
Another thing you could try is running a more verbose mode of `spin provision`:

```bash
spin provision --user root -vvvv
```

That should give you a lot of output 😃

Hope this helps! Let me know if you have any other error messages that could help figure out what's going on. Not sure if this is all related to the 1password stuff or not.

**Comment by nckrtl** [comment]
When doing the docker run command I see the following log:
```
+ '[' nckrtl '!=' ansible ]
+ debug_print 'Renaming user "ansible" to "nckrtl"...'
+ '[' true '=' true ]
+ echo 'Renaming user "ansible" to "nckrtl"...'
Renaming user "ansible" to "nckrtl"...
+ '[' -f /etc/alpine-release ]
+ usermod -l nckrtl ansible
+ groupmod -n nckrtl ansible
+ usermod -d /home/nckrtl -m nckrtl
+ '[' -f /etc/debian_version ]
+ debug_print 'User and group renamed successfully. Home directory updated.'
+ '[' true '=' true ]
+ echo 'User and group renamed successfully. Home directory updated.'
User and group renamed successfully. Home directory updated.
+ mkdir -p /Users
+ ln -s /home/nckrtl /Users/nckrtl
+ '[' '!' -z 501 ]
+ '[' 501 '!=' 1000 ]
+ debug_print 'Preparing environment for 501:20...'
+ '[' true '=' true ]
+ echo 'Preparing environment for 501:20...'
Preparing environment for 501:20...
+ id -u 501
+ getent group 20
+ getent group 20
+ cut -d: -f1
+ old_group=dialout
+ debug_print 'GID 20 already exists for group dialout. Moving to a new GID.'
+ '[' true '=' true ]
+ echo 'GID 20 already exists for group dialout. Moving to a new GID.'
GID 20 already exists for group dialout. Moving to a new GID.
+ groupmod -g 99920 dialout
+ usermod -u 501 nckrtl
+ groupmod -g 20 nckrtl
+ debug_print 'Changing ownership of all files and directories...'
+ '[' true '=' true ]
+ echo 'Changing ownership of all files and directories...'
Changing ownership of all files and directories...
+ chown 501:20 /home/nckrtl /home/nckrtl/.ssh /etc/ansible /ssh
+ '[' '!' -z 501 ]
+ '['  ]
+ debug_print 'Running command as "nckrtl"...'
+ '[' true '=' true ]
+ echo 'Running command as "nckrtl"...'
Running command as "nckrtl"...
+ switch_user sh
+ command -v su-exec
+ exec su-exec nckrtl sh
```

Then when doing `cd ~; ls -la` I see:
```
drwxr-sr-x    1 nckrtl   nckrtl          32 Oct  9 20:22 .
drwxr-xr-x    1 root     root            26 Oct  9 20:21 ..
-rw-------    1 nckrtl   nckrtl          15 Oct  9 20:22 .ash_history
lrwxrwxrwx    1 root     1000             4 Oct  9 18:22 .ssh -> /ssh
```
Which seems to match what you describe

The content of .ssh indeed matches my local .ssh directory. But I cannot ssh into my VPS from within that docker container.

I did a `spin provision --user root -vvvv` without the changes in run_ansible(). I then get:
```
<vps-ip> ESTABLISH SSH CONNECTION FOR USER: root
<vps-ip>  SSH: EXEC ssh -vvvv -C -o ControlMaster=auto -o ControlPersist=60s -o Port=22 -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="root"' -o ConnectTimeout=10 -o IgnoreUnknown=UseKeychain -o 'ControlPath="/home/nckrtl/.ansible/cp/d426ac9f2d"' <vps-ip> '/bin/sh -c '"'"'echo ~root && sleep 0'"'"''
``` 
and a massive error where it seems to go through all directories that could contain a ssh config or a private key but doesnt find any that allows it to connect to the server. Im not comfortable sharing to full error as its long and contains Ip addresses and file name of my .ssh content.

when I remove
```
    -e "PUID=${SPIN_USER_ID}" \
    -e "PGID=${SPIN_GROUP_ID}" \
    -e "RUN_AS_USER=$(whoami)" \
```

The log looks like:
```
 <vps-ip>  ESTABLISH SSH CONNECTION FOR USER: root
 <vps-ip>  SSH: EXEC ssh -vvvv -C -o ControlMaster=auto -o ControlPersist=60s -o Port=22 -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="root"' -o ConnectTimeout=10 -o IgnoreUnknown=UseKeychain -o 'ControlPath="/root/.ansible/cp/d426ac9f2d"'  <vps-ip>  '/bin/sh -c '"'"'echo ~root && sleep 0'"'"''
```
And right after that I get the question to trust the host and then get the 1password prompt.

So it feels like a permission issue where it cant read/process the ssh config in the container when using my local username nckrtl

**Comment by jaydrogers** [comment]
> The content of .ssh indeed matches my local .ssh directory. But I cannot ssh into my VPS from within that docker container.

I would start here.

Any clues with running this **inside of the container**?

```
ssh -vvvv user@host
```

**Comment by jaydrogers** [comment]
Also, could you potentially post your permissions of `~/.ssh` from within the container (if it doesn’t leak any private data).

Getting an understanding of what a `ls -al ~/.ssh` from within the container might point to some more clues too.

There are so many moving parts to SSH 😆

**Comment by nckrtl** [comment]
Alright I'm back at it. So with:
```
docker run --rm -it \
    -v "$HOME/.ssh/:/ssh/" \
    -e "PUID=$(id -u)" \
    -e "PGID=$(id -g)" \
    -e "RUN_AS_USER=$(whoami)" \
    -e "DEBUG=true" \
    docker.io/serversideup/ansible-core:2.17-alpine sh
```
I can't ssh into the vps from the container , but it works with:
```
docker run --rm -it \
    -v "$HOME/.ssh/:/ssh/" \
    -e "PUID=$(id -u)" \
    -e "PGID=$(id -g)" \
    -e "RUN_AS_USER=$(whoami)" \
    -e "DEBUG=true" \
    -e SSH_AUTH_SOCK=/run/host-services/ssh-auth.sock \ <--- with this option added
    docker.io/serversideup/ansible-core:2.17-alpine sh
```

So I ran the -vvvv option. And the difference is that `ssh_get_authentication_socket_path` is pointing to my local path which is outside the container but can somehow be read. Probably the magic provided by `-e SSH_AUTH_SOCK=/run/host-services/ssh-auth.sock`. And with the first option `ssh_get_authentication_socket_path` points to a path inside the container. But it then can't find the 1password ssh agent.sock as it's not available/mounted in the container. 

But I think this is all unrelated to the original issue for provisioning for example. What I forgot to mention is that I provision my servers with `spin provision -u root`. In that case the final docker run command will be this:
```
docker run --rm -it \
    -e "PUID=$(id -u)" \
    -e "PGID=$(id -g)" \
    -e "RUN_AS_USER=$(whoami)" \
    -v /Users/nckrtl/.ssh/:/ssh/ \
    -v /Users/nckrtl/.spin/cache/collections:/etc/ansible/collections \
    -v /run/host-services/ssh-auth.sock:/run/host-services/ssh-auth.sock \
    -e SSH_AUTH_SOCK=/run/host-services/ssh-auth.sock \
    -v /Users/nckrtl/Projects/spin-traefik:/ansible \
    docker.io/serversideup/ansible-core:2.17-alpine \
    ansible-playbook serversideup.spin.provision --inventory ./.spin-inventory.ini --extra-vars @./.spin.yml --extra-vars ansible_user=root
```
If just run `spin provision` the ansible user will be nckrtl:
```
docker run --rm -it \
    -e "PUID=$(id -u)" \
    -e "PGID=$(id -g)" \
    -e "RUN_AS_USER=$(whoami)" \
    -v /Users/nckrtl/.ssh/:/ssh/ \
    -v /Users/nckrtl/.spin/cache/collections:/etc/ansible/collections \
    -v /run/host-services/ssh-auth.sock:/run/host-services/ssh-auth.sock \
    -e SSH_AUTH_SOCK=/run/host-services/ssh-auth.sock \
    -v /Users/nckrtl/Projects/spin-traefik:/ansible \
    docker.io/serversideup/ansible-core:2.17-alpine \
    ansible-playbook serversideup.spin.provision --inventory ./.spin-inventory.ini --extra-vars @./.spin.yml --extra-vars ansible_user=nckrtl
```
So in that case `RUN_AS_USER` and `ansible user` are the same but when you use `-u root` that isn't the case. 

I believe thats the reason why provisioning with `spin provision -u root` works when removing:
```
    -e "PUID=$(id -u)" \
    -e "PGID=$(id -g)" \
    -e "RUN_AS_USER=$(whoami)" \
```

So my current assumption is that `RUN_AS_USER` and the `ansible_user` should always be the same. Or, if the ansible_user is root the options:
```
    -e "PUID=$(id -u)" \
    -e "PGID=$(id -g)" \
    -e "RUN_AS_USER=$(whoami)" \
```
Should be omitted from the final docker run command

**Comment by nckrtl** [comment]
Closing this. As discussed over Discord this issue is now resolved.

To make 1password ssh work with provisioning and deploying and other actions that involves ssh, you need to update your ssh config from
```
Host *
   IdentityAgent "~/Library/Group Containers/2BUA8C4S2C.com.1password/t/agent.sock"
```
To:
```
Host *
   ForwardAgent yes
```

And make sure the following env value is available in your bash environment:
```
SSH_AUTH_SOCK=~/Library/Group\ Containers/2BUA8C4S2C.com.1password/t/agent.sock
```

Now it should all work.
